/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Extract project ID from Supabase URL or use fallback
const extractProjectId = (url: string | undefined): string => {
  if (!url) return "zswnntasyipwohmtyzor";
  
  try {
    const match = url.match(/https:\/\/([^.]+)\.supabase\.co/);
    return match ? match[1] : "zswnntasyipwohmtyzor";
  } catch {
    return "zswnntasyipwohmtyzor";
  }
};

// Use environment variables in production, fallback to development values
export const projectId = extractProjectId(import.meta.env?.VITE_SUPABASE_URL);
export const publicAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzd25udGFzeWlwd29obXR5em9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjM4MDMsImV4cCI6MjA3NDUzOTgwM30.DVw9WPjBcLinb9XcOtSkRntPbO9hS6R09GUW2z7hVJg";